/*
@docs ARCHITECTURE:UI

### AI Assist Note
**🛡️ Tadpole OS: Artifactpromotioncard**
Core system module providing specialized functionality for the agent swarm.

### 🔍 Debugging & Observability
- **Failure Path**: Unexpected execution drift or type compatibility issues.
- **Telemetry Link**: Traced via active system logging channels.
*/

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Rocket, Check, AlertCircle, Terminal, FileCode, Shield } from 'lucide-react';
import clsx from 'clsx';
import { i18n } from '../../i18n';

interface ArtifactPromotionCardProps {
    name: string;
    content: string;
    agentId: string;
    missionId?: string;
    onPromoted?: (id: string) => void;
}

export const ArtifactPromotionCard: React.FC<ArtifactPromotionCardProps> = ({
    name,
    content,
    agentId,
    missionId,
    onPromoted
}) => {
    const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
    const [error, setError] = useState<string | null>(null);

    const handlePromote = async () => {
        setStatus('loading');
        try {
            const response = await fetch('/v1/skills/promote', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('NEURAL_TOKEN')}`
                },
                body: JSON.stringify({
                    name,
                    description: `Autonomous tool generated by Agent ${agentId}`,
                    cap_type: 'skill',
                    content,
                    agent_id: agentId,
                    mission_id: missionId
                })
            });

            if (!response.ok) throw new Error(await response.text());
            
            const data = await response.json();
            setStatus('success');
            onPromoted?.(data.id);
        } catch (err: unknown) {
            setStatus('error');
            setError(err instanceof Error ? err.message : String(err));
        }
    };

    return (
        <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-4 p-4 rounded-xl bg-zinc-900/80 border border-zinc-700/50 backdrop-blur-md shadow-2xl overflow-hidden relative group"
        >
            <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-purple-500 to-blue-500" />
            
            <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-zinc-800 border border-zinc-700 text-purple-400 shadow-inner">
                        <FileCode size={18} />
                    </div>
                    <div>
                        <h4 className="text-[11px] font-bold text-zinc-100 uppercase tracking-widest">
                            {i18n.t('evolution.artifact_detected')}
                        </h4>
                        <p className="text-[10px] text-zinc-400 font-mono mt-0.5">
                            {name}.py
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <div className="flex -space-x-1">
                        <div className="w-4 h-4 rounded-full bg-zinc-700 border border-zinc-800 flex items-center justify-center">
                           <Shield size={8} className="text-zinc-400" />
                        </div>
                    </div>
                    <span className="text-[8px] text-zinc-500 font-mono uppercase">Lvl 1 Autonomy</span>
                </div>
            </div>

            <div className="mt-4 p-3 rounded-lg bg-black/40 border border-white/5 font-mono text-[9px] text-zinc-500 max-h-24 overflow-hidden relative">
                <pre className="line-clamp-4">{content}</pre>
                <div className="absolute bottom-0 left-0 w-full h-8 bg-gradient-to-t from-black/80 to-transparent" />
            </div>

            <div className="mt-4 flex items-center justify-between">
                <div className="flex items-center gap-2 text-[9px] text-zinc-500 italic">
                    <Terminal size={10} />
                    <span>Evolution proposal awaiting oversight</span>
                </div>

                <button
                    onClick={handlePromote}
                    disabled={status === 'loading' || status === 'success'}
                    className={clsx(
                        "px-4 py-2 rounded-lg flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider transition-all duration-300 shadow-lg",
                        status === 'idle' && "bg-purple-600 hover:bg-purple-500 text-white shadow-purple-900/20",
                        status === 'loading' && "bg-zinc-800 text-zinc-500 cursor-wait",
                        status === 'success' && "bg-green-600/20 text-green-400 border border-green-500/30 cursor-default",
                        status === 'error' && "bg-red-600/20 text-red-400 border border-red-500/30"
                    )}
                >
                    {status === 'idle' && (
                        <>
                            <Rocket size={14} className="group-hover:animate-bounce" />
                            {i18n.t('evolution.btn_promote')}
                        </>
                    )}
                    {status === 'loading' && (
                        <>
                            <div className="w-3 h-3 border-2 border-zinc-500 border-t-zinc-100 rounded-full animate-spin" />
                            {i18n.t('evolution.processing')}
                        </>
                    )}
                    {status === 'success' && (
                        <>
                            <Check size={14} />
                            {i18n.t('evolution.proposed')}
                        </>
                    )}
                    {status === 'error' && (
                        <>
                            <AlertCircle size={14} />
                            {i18n.t('evolution.retry')}
                        </>
                    )}
                </button>
            </div>

            <AnimatePresence>
                {status === 'error' && error && (
                    <motion.p 
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="mt-2 text-[8px] text-red-400 font-mono text-center border-t border-red-500/10 pt-2"
                    >
                        Error: {error}
                    </motion.p>
                )}
            </AnimatePresence>
        </motion.div>
    );
};

// Metadata: [ArtifactPromotionCard]

// Metadata: [ArtifactPromotionCard]
