//! Type Synchronization Utility — Rust to TypeScript
//!
//! @docs ARCHITECTURE:Toolchain
//!
//! ### AI Assist Note
//! **Schema Generator**: Automatically exports Rust struct and enum definitions 
//! to TypeScript interfaces using `specta`. This eliminates "Type Drift" 
//! between the engine and the UI visualizers (MOD-01).

use specta_typescript::Typescript;
use crate::agent::mcp::{McpToolHub, McpToolStats, McpResult};
use crate::telemetry::pulse_types::{PulseNode, PulseConnection, SwarmPulse};

/// Exports core engine types to TypeScript.
/// Path: `src/types/schemas.ts` (relative to WORKSPACE_ROOT)
pub fn export_types() -> Result<(), Box<dyn std::error::Error>> {
    let workspace_root = std::env::var("WORKSPACE_ROOT").unwrap_or_else(|_| ".".to_string());
    let ts_path = std::path::PathBuf::from(workspace_root).join("src").join("types").join("schemas.ts");
    
    println!("🧬 [Schema] Exporting TypeScript schemas to {}...", ts_path.display());
    
    let mut ts_output = String::new();
    ts_output.push_str("// 🧬 AUTO-GENERATED TADPOLE OS SCHEMAS - DO NOT EDIT MANUALLY\n");
    ts_output.push_str("// Generated by server-rs/src/utils/schema_gen.rs\n\n");
    
    let mut types = specta::TypeCollection::default();
    types.register::<McpToolStats>();
    types.register::<McpToolHub>();
    types.register::<McpResult>();
    types.register::<PulseNode>();
    types.register::<PulseConnection>();
    types.register::<SwarmPulse>();
    types.register::<crate::intelligence::graph::SymbolNode>();
    
    // Core Agent & Model Registry
    types.register::<crate::agent::types::EngineAgent>();
    types.register::<crate::agent::types::AgentIdentity>();
    types.register::<crate::agent::types::AgentModels>();
    types.register::<crate::agent::types::AgentEconomics>();
    types.register::<crate::agent::types::AgentHealth>();
    types.register::<crate::agent::types::AgentCapabilities>();
    types.register::<crate::agent::types::AgentState>();
    types.register::<crate::agent::types::ModelProvider>();
    types.register::<crate::agent::types::ModelConfig>();
    types.register::<crate::agent::types::ProviderStatus>();
    types.register::<crate::agent::types::MissionStatus>();
    types.register::<crate::agent::types::TokenUsage>();
    types.register::<crate::agent::types::RoleAuthorityLevel>();
    types.register::<crate::agent::types::Modality>();
    types.register::<crate::agent::types::ConnectorConfig>();
    types.register::<crate::agent::types::ModelEntry>();
    types.register::<crate::agent::types::ProviderConfig>();
    types.register::<crate::agent::types::RoleBlueprint>();
    
    let exporter = Typescript::default();
    let result = exporter.export(&types).map_err(|e| e.to_string())?;
    ts_output.push_str(&result);
    
    // Ensure parent directory exists
    if let Some(parent) = ts_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    
    std::fs::write(ts_path, ts_output)?;
    println!("✅ [Schema] Export complete.");
    Ok(())
}
