// 🧬 AUTO-GENERATED TADPOLE OS SCHEMAS - DO NOT EDIT MANUALLY
// Generated by server-rs/src/utils/schema_gen.rs

// This file has been generated by Specta. DO NOT EDIT.

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type McpResult = { type: "Raw"; data: string } | { type: "SystemDelegate"; data: [string, JsonValue] }

/**
 * A structured tool definition registered within the MCP ecosystem.
 */
export type McpToolHub = { name: string; description: string; input_schema: JsonValue; source: string; stats: McpToolStats; category: string }

/**
 * Operational statistics for a specific tool.
 */
export type McpToolStats = { invocations: number; success_count: number; failure_count: number; avg_latency_ms: number }

export type PulseConnection = { source: string; target: string }

export type PulseNode = { id: string; x: number; y: number; status: number; battery: number; signal: number; progress: number }

export type SwarmPulse = { timestamp: number; nodes: PulseNode[]; edges: PulseConnection[] }

/**
 * A node in the knowledge graph representing a code symbol.
 */
export type SymbolNode = { name: string; path: string; kind: string; signature: string }

