/*
@docs ARCHITECTURE:SovereignKernel

### AI Assist Note
**🛡️ Tadpole OS: Schemas**
Core system module providing specialized functionality for the agent swarm.

### 🔍 Debugging & Observability
- **Failure Path**: Unexpected execution drift or type compatibility issues.
- **Telemetry Link**: Traced via active system logging channels.
*/

// 🧬 AUTO-GENERATED TADPOLE OS SCHEMAS - DO NOT EDIT MANUALLY
// Generated by server-rs/src/utils/schema_gen.rs

// This file has been generated by Specta. DO NOT EDIT.

export type AgentCapabilities = { skills: string[]; workflows: string[]; mcpTools: string[]; skillManifest: SkillManifest | null }

export type AgentEconomics = { budgetUsd: number; costUsd: number; tokensUsed: number; tokenUsage: TokenUsage }

export type AgentHealth = { status: string; failureCount: number; lastFailureAt: string | null; heartbeatAt: string | null }

export type AgentIdentity = { id: string; name: string; role: string; department: string; description: string; category: string; themeColor: string | null }

export type AgentModels = { modelId: string | null; model: ModelConfig; model2: string | null; model3: string | null; modelConfig2: ModelConfig | null; modelConfig3: ModelConfig | null; activeModelSlot: number | null }

export type AgentState = { activeMission: JsonValue | null; currentTask: string | null; workingMemory: JsonValue; currentReasoningTurn: number }

export type ConnectorConfig = { type: string; uri: string }

export type DangerLevel = "low" | "medium" | "high" | "critical"

export type EngineAgent = { identity: AgentIdentity; models: AgentModels; economics: AgentEconomics; health: AgentHealth; capabilities: AgentCapabilities; state: AgentState; metadata: Partial<{ [key in string]: JsonValue }>; created_at: string | null; requires_oversight: boolean; voice_id: string | null; voice_engine: string | null; stt_engine: string | null; connector_configs: ConnectorConfig[]; version: number }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type McpResult = { type: "Raw"; data: string } | { type: "SystemDelegate"; data: [string, JsonValue] }

/**
 * A structured tool definition registered within the MCP ecosystem.
 */
export type McpToolHub = { name: string; description: string; input_schema: JsonValue; source: string; stats: McpToolStats; category: string }

/**
 * Operational statistics for a specific tool.
 */
export type McpToolStats = { invocations: number; success_count: number; failure_count: number; avg_latency_ms: number }

export type MissionStatus = "pending" | "active" | "completed" | "failed" | "paused"

export type Modality = "llm" | "vision" | "voice" | "audio" | "reasoning"

export type ModelCapabilities = { supportsTools?: boolean; supportsVision?: boolean; supportsStructuredOutput?: boolean; supportsReasoning?: boolean; supportsHaltingTool?: boolean; contextWindow?: number; maxOutputTokens?: number }

export type ModelConfig = { modelId?: string; provider?: ModelProvider; systemPrompt?: string | null; apiKey?: string | null; baseUrl?: string | null; temperature?: number | null; maxTokens?: number | null; topP?: number | null; externalId?: string | null; rpm?: number | null; rpd?: number | null; tpm?: number | null; tpd?: number | null; skills?: string[] | null; workflows?: string[] | null; mcpTools?: string[] | null; steeringVectors?: string[] | null; reasoningDepth?: number | null; actThreshold?: number | null; maxTurns?: number | null; connectorConfigs?: ConnectorConfig[] | null; extraParameters?: Partial<{ [key in string]: JsonValue }> | null }

export type ModelEntry = { id: string; name: string; providerId: string; provider?: ModelProvider | null; rpm?: number | null; tpm?: number | null; rpd?: number | null; tpd?: number | null; modality?: Modality; capabilities?: ModelCapabilities }

/**
 * ### 📡 Protocol: ModelProvider
 * Defines the set of supported LLM backend protocols for the Tadpole OS engine.
 */
export type ModelProvider = "openai" | "anthropic" | "google" | "gemini" | "ollama" | "groq" | "mistral" | "perplexity" | "fireworks" | "together" | "deepseek" | "xai" | "inception" | "openrouter" | "cerebras" | "sambanova" | "meta" | "alibaba" | "local"

export type Permission = "network:outbound" | "filesystem:read" | "filesystem:write" | "shell:execute" | "budget:spend" | { unknown: string }

export type ProviderConfig = { id: string; name: string; icon: string | null; apiKey?: string | null; baseUrl?: string | null; protocol: ModelProvider; externalId?: string | null; customHeaders?: Partial<{ [key in string]: string }> | null; defaultConfig?: ModelConfig | null; supportsSteeringVectors?: boolean; audioModel?: string | null }

/**
 * ### 📡 Protocol: ProviderStatus
 * Represents the health state of an LLM provider.
 * - Green: Healthy, all models functional.
 * - Amber: Degraded, high failure rate or rate limited. Diverts to secondary.
 * - Red: Down, critical failures. Fails over to fallback or NullProvider.
 */
export type ProviderStatus = "green" | "amber" | "red"

export type PulseConnection = { source: string; target: string }

export type PulseNode = { id: string; x: number; y: number; status: number; battery: number; signal: number; progress: number }

/**
 * ### 📡 Protocol: RoleAuthorityLevel
 * Defines the authority level of an agent in the swarm.
 */
export type RoleAuthorityLevel = 
/**
 * Executive level (CEO, COO) - Strategic oversight and delegation.
 */
"executive" | 
/**
 * Management level (Alpha Node) - Tactical coordination.
 */
"management" | 
/**
 * Specialist level - Task execution.
 */
"specialist" | 
/**
 * Observer level - Read-only oversight.
 */
"observer"

export type RoleBlueprint = { id: string; name: string; department: string; description: string; skills?: string; workflows?: string; mcpTools?: string; requiresOversight?: boolean; modelId?: string | null; createdAt?: string | null }

export type SkillHooks = { before_execute: string | null; after_execute: string | null }

export type SkillManifest = { schema_version: string; name: string; display_name: string | null; description: string; version: string; author: string | null; permissions?: Permission[]; toolset_group: string | null; danger_level: DangerLevel; requires_oversight?: boolean; parameters?: Partial<{ [key in string]: SkillParameter }>; hooks: SkillHooks | null; category?: string }

export type SkillParameter = { type: string; required: boolean | null; default: JsonValue | null }

export type SwarmPulse = { timestamp: number; nodes: PulseNode[]; edges: PulseConnection[] }

/**
 * A node in the knowledge graph representing a code symbol.
 */
export type SymbolNode = { name: string; path: string; kind: string; signature: string }

export type TokenUsage = { inputTokens?: number; outputTokens?: number; totalTokens?: number }


// Metadata: [schemas]

// Metadata: [schemas]
