import os
import re

def scan_codebase(root_dir):
    findings = []
    # Patterns for common Rust "Kernel Faults"
    patterns = {
        "Unhandled Unwrap": re.compile(r"\.unwrap\(\)"),
        "Unhandled Expect": re.compile(r"\.expect\("),
        "Potential Panic": re.compile(r"panic!\("),
        "Blocking std::fs": re.compile(r"std::fs::")
    }

    src_dir = os.path.join(root_dir, "server-rs", "src")
    
    for root, dirs, files in os.walk(src_dir):
        for file in files:
            if file.endswith(".rs"):
                path = os.path.join(root, file)
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        for i, line in enumerate(f, 1):
                            for name, pattern in patterns.items():
                                if pattern.search(line):
                                    findings.append({
                                        "file": os.path.relpath(path, root_dir),
                                        "line": i,
                                        "type": name,
                                        "snippet": line.strip()
                                    })
                except Exception as e:
                    print(f"Error reading {path}: {e}")
    
    return findings

def generate_report(findings, output_path):
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Sovereign Audit: Kernel Fault Report\n\n")
        f.write("This report was generated by the Nexus Engineer using a deep-static analysis sweep.\n\n")
        f.write("| File Path | Line | Fault Type | Code Snippet |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")
        
        for item in findings:
            # Escape pipes for markdown table
            snippet = item['snippet'].replace("|", "\\|")
            f.write(f"| `{item['file']}` | {item['line']} | **{item['type']}** | `{snippet}` |\n")

if __name__ == "__main__":
    ROOT = r"D:\Autonomous-Agentic-Tadpole"
    OUTPUT = os.path.join(ROOT, "audit_full_report.md")
    
    print("[Nexus] Starting Sovereign Audit Scan...")
    findings = scan_codebase(ROOT)
    print(f"[Nexus] Scan complete. Found {len(findings)} potential faults.")
    generate_report(findings, OUTPUT)
    print(f"[Nexus] Report generated at: {OUTPUT}")
